apiVersion: v1
kind: Service
metadata:
  name: jira-clone-web
spec:
  selector:
    app: jira-clone-web
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001